routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){

 
    sendMail("www.princearora@gmail.com","OTP Verification for Email","mails.text",['text'=>'Hello there ']);

});

Route::get('login',['as'=>'login','uses'=>"LoginController@index"]);

Route::post('login',['as'=>'login','uses'=>"LoginController@login"]);

Route::group(['middleware'=>'Admin'],function(){

    Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);

    Route::get('/',['as'=>'home','uses'=>"ViewController@home"]);

    Route::resource('types','CampaignTypeController');

    Route::resource('states','StateController');

    Route::resource('cities','CityController');

    Route::resource('ngos','NgoController');

    Route::resource('users','UserController');

  
   
    Route::resource('cms','CmsController');

    Route::resource('campaigns','CampaignController');

    Route::get('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@gallery']);

    Route::post('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@galleryStore']);

    Route::delete('campaigns/gallery/{image_id}',['as'=>'campaigns.gallery.destroy','uses'=>'CampaignController@galleryDestroy']);
    
    

    Route::group(['prefix'=>'ajax','as'=>'ajax.'],function(){

        Route::post('upload/media',['as'=>'uploadMedia','uses'=>'AjaxController@uploadMedia']);

        Route::any('get/cities/{state_id?}',['as'=>'getCities','uses'=>'AjaxController@getCities']);

    });

});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;


class City extends Model
{
    //
    protected $fillable = ['title','is_active','state_id'];
    protected static function booted()
    {
        static::addGlobalScope('only_active', function (Builder $builder) {
            $builder->where('cities.is_active', 1);
        });

        // static::addGlobalScope('only_india', function (Builder $builder) {
        //     $builder->join('states','states.id','=','cities.state_id')
        //             ->where('states.country_id', 101);
        // });
    }

    public function state(){
        return $this->hasOne('App\State','id','state_id');
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use \Validator;

use App\DataTables\CitiesDataTable;
use App\State;
use App\City;

class CityController extends Controller
{

    protected $attributes =[
        'title',
        'state_id',
        'is_active'
    ];

    protected $validationRules = [
        'title'=>'required|min:2|regex:/^[\pL\s\-]+$/u|max:300|unique:cities,title,NULL,id,deleted_at,NUll',
         'is_active'=>'required|in:1,0',                                
        'state_id'=>"required|exists:states,id"
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CitiesDataTable $table)
    {
        //
        return $table->render('cities.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $states = State::all();
        return view('cities.create',compact('states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = Arr::only($request->all(),$this->attributes);
        $validate = Validator::make($input,$this->validationRules);
        if($validate->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validate);
        
        if(City::create($input)){
            flash()->ok("City added successfully !");
            return redirect()->route('cities.index');
        }
        flash()->e();
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $City = City::withoutGlobalScope('only_active')->select('cities.*')->findOrFail($id);
        $states = State::all();
        return view('cities.edit',compact('City','states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Sector = City::withoutGlobalScope('only_active')
                        
                                    ->select('cities.*')
                                    ->findOrFail($id);
        $rules = $this->validationRules;
        $rules['title']="required|min:2|regex:/^[\pL\s\-]+$/u|max:300|unique:cities,title,$id,id,deleted_at,NUll";
        $input = Arr::only($request->all(),$this->attributes);
        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validate);
        
        if($Sector->update($input)){
            flash()->ok("City updated successfully !");
            return redirect()->route('cities.index');
        }
        flash()->e();
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(City::findOrFail($id)->delete())
             return api()->success(['message'=>"Action completed successfully !"]);

        return api()->error();
    }
}

resources/views/cities/actions.blade.php
<div class='btn-group btn-group-sm'>
  <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('cities.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  <a onclick="trashUtil(this)" trash-url="{{ route('cities.destroy', $id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
    <i class="fa fa-trash"></i>
  </a>
</div>

resources/views/cities/create.blade.php
@extends('layouts.default')
@section('title','Create City')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Create City</h6> <a href="{{route('cities.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to Cities</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('cities.store')}}" enctype="multipart/form-data">
                @include('cities.fields')
                <div class="row">
                  <div class="col-md-12 form-group">
                    <button type="submit" class="btn btn-info float-right">Create</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/cities/edit.blade.php
@extends('layouts.default')
@section('title','Edit City')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Edit City</h6> <a href="{{route('cities.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to Cities</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('cities.update',$City->id)}}" enctype="multipart/form-data">
              @method('PUT')  
              @include('cities.fields')
                <div class="col-md-12 form-group">
                  <button type="submit" class="btn btn-success float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/cities/fields.blade.php
<div class="row">
    {!! csrf_field() !!}
    
    <div class="col-md-3 form-group">
        <label>Active</label>
        <select class="form-control" name="is_active">
        @foreach(['No','Yes'] as $g=>$t)
        <option {{old('is_active',$City->is_active??null)==$g?'selected':''}} value="{{$g}}">{{$t}}</option>
        @endforeach
        </select>
        <p class="error">
            {{$errors->first('is_active')}}
        </p>
    </div>
    <div class="col-md-3 form-group">
        <label>State</label>
        <select class="form-control" name="state_id">
            @foreach($states as $state)
            <option {{old('state_id',$City->state_id??null)==$state->id?'selected':''}} value="{{$state->id}}">{{$state->title}}</option>
            @endforeach
        </select>
        <p class="error">
            {{$errors->first('state_id')}}
        </p>
    </div>
    
    <div class="col-md-6 form-group">
        <label>City</label>
        <input type="text" name="title" placeholder="City TItle goes here "  class="form-control" value="{{old('title',$City->title??'')}}" />
        <p class="error">
            {{$errors->first('title')}}
        </p>
    </div>

   
    
</div>

resources/views/cities/index.blade.php
@extends('layouts.default')
@section('title','Cities')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Cities</h6> <a href="{{route('cities.create')}}" class="btn btn-default float-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create City</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            {{$dataTable->table()}}
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')
{{$dataTable->scripts()}}
<script>
   
</script>
@endpush