routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){

 
    sendMail("www.princearora@gmail.com","OTP Verification for Email","mails.text",['text'=>'Hello there ']);

});

Route::get('login',['as'=>'login','uses'=>"LoginController@index"]);

Route::post('login',['as'=>'login','uses'=>"LoginController@login"]);

Route::group(['middleware'=>'Admin'],function(){

    Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);

    Route::get('/',['as'=>'home','uses'=>"ViewController@home"]);

    Route::resource('types','CampaignTypeController');

    Route::resource('states','StateController');

    Route::resource('cities','CityController');

    Route::resource('ngos','NgoController');

    Route::resource('users','UserController');

  
   
    Route::resource('cms','CmsController');

    Route::resource('campaigns','CampaignController');

    Route::get('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@gallery']);

    Route::post('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@galleryStore']);

    Route::delete('campaigns/gallery/{image_id}',['as'=>'campaigns.gallery.destroy','uses'=>'CampaignController@galleryDestroy']);
    
    

    Route::group(['prefix'=>'ajax','as'=>'ajax.'],function(){

        Route::post('upload/media',['as'=>'uploadMedia','uses'=>'AjaxController@uploadMedia']);

        Route::any('get/cities/{state_id?}',['as'=>'getCities','uses'=>'AjaxController@getCities']);

    });

});

app/Cms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cms extends Model
{
    //
    protected $table='cms';
    
    protected $fillable = [
        'slug',
        'title',
        'content'
    ];  
}

app/Http/Controllers/CmsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

use \Validator;

use App\DataTables\CmsDataTable;
use App\Cms;

class CmsController extends Controller
{
    protected $attributes = [
        'title',
        'content',
        'description'
    ];

    protected $validationRules =[
        'title'=>'required|min:2|max:200',
        'content'=>'required',
        
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CmsDataTable $table)
    {
        //
        return $table->render('cms.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        $input = Arr::only($req->all(),$this->attributes);
        $rules = $this->validationRules;

        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withErrors($validate)->withInput($req->all());

        $slug = Str::slug($input['title']);
        if(Cms::whereSlug($slug)->count()){
            do{
                $slug=$slug.'-'.mt_rand(1,9999);
            }while(Cms::whereSlug($slug)->count());
        }
        
        $input['slug']=$slug;
        
           
        
       if(Cms::create($input)){
           flash()->ok('Content added Successfully !');
           return redirect()->route('cms.index');
       }

       flash()->err();
       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Cms = Cms::findOrFail($id);

        return view('cms.edit',compact('Cms'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        $Cms = Cms::findOrFail($id);

        $input = Arr::only($req->all(),$this->attributes);
        $rules = $this->validationRules;

        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withErrors($validate)->withInput($req->all());
        
        $Cms->delete();    
            
        $slug = Str::slug($input['title']);
       
        if(Cms::whereSlug($slug)->count()){
            do{
                $slug=$slug.'-'.mt_rand(1,9999);
            }while(Cms::whereSlug($slug)->count());
        }
        
        $input['slug']=$slug;
        
           
        
       if(Cms::create($input)){
           flash()->ok('Content updated Successfully !');
           return redirect()->route('cms.index');
       }

       flash()->err();
       return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Cms::findOrFail($id)->delete())
            return api()->success(['message'=>"Content deleted successfully !"]);

        return api()->error();
    }
}

resources/views/cms/actions.blade.php
<div class='btn-group btn-group-sm'>
  <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('cms.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  <a onclick="trashUtil(this)" trash-url="{{ route('cms.destroy', $id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
    <i class="fa fa-trash"></i>
  </a>
</div>

resources/views/cms/create.blade.php
@extends('layouts.default')
@section('title','Create Content')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Create Content</h6> <a href="{{route('cms.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to CMS</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('cms.store')}}" enctype="multipart/form-data">
                @include('cms.fields')
                <div class="row">
                  <div class="col-md-12 form-group">
                    <button type="submit" class="btn btn-info float-right">Create</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/cms/edit.blade.php
@extends('layouts.default')
@section('title','Edit Content')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Edit Content</h6> <a href="{{route('cms.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to Cms</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('cms.update',$Cms->id)}}" enctype="multipart/form-data">
              @method('PUT')  
              @include('cms.fields')
                <div class="col-md-12 form-group">
                  <button type="submit" class="btn btn-success float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/cms/fields.blade.php
<div class="row">
    {!! csrf_field() !!}
    <div class="col-md-12  form-group">
        <label>Name</label>
        <input type="text" name="title"  class="form-control" value="{{old('title',$Cms->title??'')}}" />
        <p class="error">
            {{$errors->first('title')}}
        </p>
    </div>

   
    <div class="col-md-12 form-group">
        <label>Content<small></small></label>
        <textarea name="content" rows="10"  id="t_content" class="form-control">{{old('content',$Cms->content??'')}}</textarea>
        <p class="error">
            {{$errors->first('content')}}
        </p>
    </div>
    
</div>

@push('scripts')
<script src="{{url('assets\vendor\ckeditor5\ckeditor.js')}}"></script>
<script>
    const READY = ()=>{
        CKEDITOR.replace('t_content');
    }
</script>
@endpush

resources/views/cms/index.blade.php
@extends('layouts.default')
@section('title','CMS')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">CMS</h6> <a href="{{route('cms.create')}}" class="btn btn-default float-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            {{$dataTable->table()}}
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')
{{$dataTable->scripts()}}
<script>
   
</script>
@endpush