routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){

 
    sendMail("www.princearora@gmail.com","OTP Verification for Email","mails.text",['text'=>'Hello there ']);

});

Route::get('login',['as'=>'login','uses'=>"LoginController@index"]);

Route::post('login',['as'=>'login','uses'=>"LoginController@login"]);

Route::group(['middleware'=>'Admin'],function(){

    Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);

    Route::get('/',['as'=>'home','uses'=>"ViewController@home"]);

    Route::resource('types','CampaignTypeController');

    Route::resource('states','StateController');

    Route::resource('cities','CityController');

    Route::resource('ngos','NgoController');

    Route::resource('users','UserController');

  
   
    Route::resource('cms','CmsController');

    Route::resource('campaigns','CampaignController');

    Route::get('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@gallery']);

    Route::post('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@galleryStore']);

    Route::delete('campaigns/gallery/{image_id}',['as'=>'campaigns.gallery.destroy','uses'=>'CampaignController@galleryDestroy']);
    
    

    Route::group(['prefix'=>'ajax','as'=>'ajax.'],function(){

        Route::post('upload/media',['as'=>'uploadMedia','uses'=>'AjaxController@uploadMedia']);

        Route::any('get/cities/{state_id?}',['as'=>'getCities','uses'=>'AjaxController@getCities']);

    });

});

app/Ngo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ngo extends Model
{
    //
    use SoftDeletes;
    protected $fillable =[
        'name',
        'registration_number',
        'logo',
        'city_id',
        'zipcode',
        'address',
    ];

    public function getLogoAttribute($v){
        return url($v);
    }
}

app/Http/Controllers/NgoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use \Validator;

use App\DataTables\StatesDataTable;
use App\State;
use App\Ngo;
 
class NgoController extends Controller
{
    protected $attributes =[
        'name',
        'registration_number',
        'logo',
        'state_id',
        'city_id',
        'zipcode',
        'address',
        
        
    ];

    protected $validationRules = [
        'name'=>'required|min:2|max:200',
        'registration_number'=>'required|min:1|max:100',
        'logo'=>'required|image|max:2000',
        'state_id'=>'required',
        'city_id'=>'required',
        'zipcode'=>'required',
        'address'=>'required|max:200',                               
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = Ngo::leftJoin('cities','cities.id','=','ngos.city_id')
                    ->select(
                        'cities.title as city',
                        'ngos.*'
                    )
                    ->orderBy('ngos.updated_at','DESC')
                    ->get();
        return view('ngos.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $states = State::orderBy('title','ASC')->select('id','title')->get();
        return view('ngos.create',compact('states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Arr::only($request->all(),$this->attributes);
        $validate = Validator::make($input,$this->validationRules);
        if($validate->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validate);
        
        $input['logo']=upload($request->file('logo'),'ngos/');

        if(Ngo::create($input)){
            flash()->ok("Ngo added successfully !");
            return redirect()->route('ngos.index');
        }
        flash()->e();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Data = Ngo::findOrFail($id);
        $states = State::orderBy('title','ASC')->select('id','title')->get();
        return view('ngos.edit',compact('Data','states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Ngo = Ngo::findOrFail($id);
        $input = Arr::only($request->all(),$this->attributes);
        $rules = $this->validationRules;
        $rules['logo']=str_replace('required','nullable',$rules['logo']);
        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validate);
        
        if($request->hasFile('logo')){
            $input['logo']=upload($request->file('logo'),'ngos/');
        }else{
            unset($input['logo']);
        }
        if($Ngo->update($input)){
            flash()->ok("Ngo updated successfully !");
            return redirect()->route('ngos.index');
        }
        flash()->e();
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Ngo::findOrFail($id)->delete())
            return api()->success(['message'=>"Action completed successfully !"]);

        return api()->error();
    }
}

resources/views/ngos/actions.blade.php
<div class='btn-group btn-group-sm'>
  <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('states.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  <a onclick="trashUtil(this)" trash-url="{{ route('states.destroy', $id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
    <i class="fa fa-trash"></i>
  </a>
</div>

resources/views/ngos/create.blade.php
@extends('layouts.default')
@section('title','Add NGO')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Add NGO</h6> <a href="{{route('ngos.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to NGOS</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('ngos.store')}}" enctype="multipart/form-data">
                @include('ngos.fields')
                <div class="row">
                  <div class="col-md-12 form-group">
                    <button type="submit" class="btn btn-info float-right">Create</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/ngos/edit.blade.php
@extends('layouts.default')
@section('title','Edit Ngo')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Edit Ngo</h6> <a href="{{route('ngos.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to NGOs</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('ngos.update',$Data->id)}}" enctype="multipart/form-data">
              @method('PUT')  
              @include('ngos.fields')
                <div class="col-md-12 form-group">
                  <button type="submit" class="btn btn-success float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/ngos/fields.blade.php
<div class="row">
    {!! csrf_field() !!}
  
    <div class="col-md-12  col-sm-12 form-group">
        <label>Organization</label>
        <input type="text" name="name"  class="form-control" value="{{old('name',$Data->name??'')}}" />
        <p class="error">
            {{$errors->first('name')}}
        </p>
    </div>
    <div class="col-md-6  col-sm-6 form-group">
        <label>Registration Number</label>
        <input type="text" name="registration_number"  class="form-control" value="{{old('registration_number',$Data->registration_number??'')}}" />
        <p class="error">
            {{$errors->first('registration_number')}}
        </p>
    </div>

    <div class="col-md-6 col-sm-6  form-group">
        <label>Logo</label>
        <input type="file" name="logo" class="form-control" />
        <p class="error">
            {{$errors->first('logo')}}
        </p>
    </div>
    

    <div class="col-md-12">
        <h4>Address</h4>
        <hr>
    </div>

    <div class="col-md-4 col-sm-4 form-group">
        <label>State</label>
        <select  class="form-control " previousValue="{{old('state_id',$Data->state_id??null)}}" target="[name='city_id']" name="state_id">
            @foreach($states as $state)
            <option {{old('state_id',$Data->state_id??null)==$state->id?'selected':''}} value="{{$state->id}}">{{$state->title}}</option>
            @endforeach
        </select>
        <p class="error">
            {{$errors->first('state_id')}}
        </p>
    </div>
    <div class="col-md-4 col-sm-4 form-group">
        <label for="">City</label>
        <select url="{{route('ajax.getCities')}}"  previousValue="{{old('city_id',$Data->city_id??null)}}"  name="city_id" id="" class="form-control">

        </select>
        <p class="error">
            {{$errors->first('city_id')}}
        </p>
    </div>

    <div class="col-md-4  col-sm-4 form-group">
        <label>Zipcode</label>
        <input type="text" name="zipcode"  class="form-control" value="{{old('zipcode',$Data->zipcode??'')}}" />
        <p class="error">
            {{$errors->first('zipcode')}}
        </p>
    </div>

    <div class="col-md-12 col-sm-12 form-group">
        <label for="">Address</label>
        <textarea name="address" id="" class="form-control" >{{old('address',$Data->address??null)}}</textarea>
        <p class="error">
            {{$errors->first('address')}}
        </p>
    </div>

    <div class="col-md-12">
        <h4>Bank Account Details</h4>
        <hr>
    </div>

    
</div>

resources/views/ngos/index.blade.php
@extends('layouts.default')
@section('title','Non Profit Organizations')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">NGOs</h6> <a href="{{route('ngos.create')}}" class="btn btn-default float-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create NGO</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
          <table class="table table-bordered table-striped d_table">
            <thead>
              <tr>
                <th>#</th>
                <th>Org.</th>
                <th>Reg. No.</th>
                <th>City</th>
                <th>Logo</th>
                <th>Updated At</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              @foreach($data as $d)
                <tr>
                  <td>
                    {{$d->id}}
                  </td>
                  <td>
                    {{$d->name}}
                  </td>
                  <td>
                    {{$d->registration_number}}
                  </td>
                  <td>
                    {{$d->city}}
                  </td>
                  <td>
                      <img src="{{$d->logo}}" style="max-height:10vh;" class="rounded" alt="">
                  </td>
                  <td>
                    {!! getDateColumn($d) !!}
                  </td>
                  <td>
                    <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('ngos.edit', $d->id) }}" class='btn btn-link'>
                      <i class="fa fa-edit"></i>
                    </a>
                    <a onclick="trashUtil(this)" trash-url="{{ route('ngos.destroy', $d->id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
                      <i class="fa fa-trash"></i>
                    </a>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

<script>
   
</script>
@endpush