routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){

 
    sendMail("www.princearora@gmail.com","OTP Verification for Email","mails.text",['text'=>'Hello there ']);

});

Route::get('login',['as'=>'login','uses'=>"LoginController@index"]);

Route::post('login',['as'=>'login','uses'=>"LoginController@login"]);

Route::group(['middleware'=>'Admin'],function(){

    Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);

    Route::get('/',['as'=>'home','uses'=>"ViewController@home"]);

    Route::resource('types','CampaignTypeController');

    Route::resource('states','StateController');

    Route::resource('cities','CityController');

    Route::resource('ngos','NgoController');

    Route::resource('users','UserController');

  
   
    Route::resource('cms','CmsController');

    Route::resource('campaigns','CampaignController');

    Route::get('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@gallery']);

    Route::post('campaigns/gallery/{campaign_id}',['as'=>'campaigns.gallery','uses'=>'CampaignController@galleryStore']);

    Route::delete('campaigns/gallery/{image_id}',['as'=>'campaigns.gallery.destroy','uses'=>'CampaignController@galleryDestroy']);
    
    

    Route::group(['prefix'=>'ajax','as'=>'ajax.'],function(){

        Route::post('upload/media',['as'=>'uploadMedia','uses'=>'AjaxController@uploadMedia']);

        Route::any('get/cities/{state_id?}',['as'=>'getCities','uses'=>'AjaxController@getCities']);

    });

});

app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    //

    protected $fillable =[
        'campaign_type_id',
        'ngo_id',
        'name',
        'description',
        'no_of_meals',
        'cost_per_meal',
        'end_date',
        'thumbnail'  
    ];

    protected $hidden = ['deleted_at']; 

    public function getThumbnailAttribute($v){
        return url($v);
    }

    public function gallery(){
        return $this->hasMany('App\Gallery','campaign_id');
    }


}

app/CampaignType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CampaignType extends Model
{
    use softDeletes;
    
    //

    protected $fillable = [
        'name',
      
    ];

  

    
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use \Validator;

use App\DataTables\StatesDataTable;
use App\State;
use App\Ngo;
use App\Campaign;
use App\CampaignType;
use App\Gallery;
 
class CampaignController extends Controller
{
    protected $attributes =[
        'campaign_type_id',
        'ngo_id',
        'name',
        'description',
        'no_of_meals',
        'cost_per_meal',
        'end_date',
        'thumbnail',
        
        
        
    ];

    protected $validationRules = [
        'name'=>'required|min:2|max:200',
        'campaign_type_id'=>'required|exists:campaign_types,id,deleted_at,NULL',
        'ngo_id'=>'required|exists:ngos,id,deleted_at,NULL',
        'name'=>'required|max:200',
        'description'=>'required',
        'no_of_meals'=>'required|numeric',
        'cost_per_meal'=>'required|numeric',
        'end_date'=>"required|date|after:",
        'thumbnail'=>'required|image',
                                       
    ];

    protected $friendlyNames = [
        'campaign_type_id'=>'Campaign Type',
        'ngo_id'=>'Non Profit Organization'
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = Campaign::orderBy('updated_at','DESC')
                    ->get();
        return view('campaigns.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $types = CampaignType::select('id','name')->get();
        $ngos = Ngo::select('id','name')->get();
        return view('campaigns.create',compact('types','ngos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Arr::only($request->all(),$this->attributes);
        $rules = $this->validationRules;
        $rules['end_date'].=Date('Y-m-d'); 
        $validate = Validator::make($input,$rules);
        $validate->setAttributeNames($this->friendlyNames);
        if($validate->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validate);
        
        $input['thumbnail']=upload($request->file('thumbnail'),'campaigns/');

        if(Campaign::create($input)){
            flash()->ok("Campaign added successfully !");
            return redirect()->route('campaigns.index');
        }
        flash()->e();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Data = Ngo::findOrFail($id);
        $states = State::orderBy('title','ASC')->select('id','title')->get();
        return view('ngos.edit',compact('Data','states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Ngo = Ngo::findOrFail($id);
        $input = Arr::only($request->all(),$this->attributes);
        $rules = $this->validationRules;
        $rules['end_date'].=Date('Y-m-d');
        $rules['thumbnail']=str_replace('required','nullable',$rules['thumbnail']);
        $validate = Validator::make($input,$rules);
        if($validate->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validate);
        
        if($request->hasFile('thumbnail')){
            $input['thumbnail']=upload($request->file('thumbnail'),'campaigns/');
        }else{
            unset($input['thumbnail']);
        }
        if($Ngo->update($input)){
            flash()->ok("Campaign updated successfully !");
            return redirect()->route('campaigns.index');
        }
        flash()->e();
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Campaign::findOrFail($id)->delete())
            return api()->success(['message'=>"Action completed successfully !"]);

        return api()->error();
    }

    public function gallery($id,Request $request){
        $Campaign = Campaign::findOrFail($id);
        $images = Gallery::whereCampaignId($id)
                            // ->latest('id')
                            ->get();
        return view('campaigns.gallery',compact('images','Campaign'));
    }

    public function galleryStore($id,Request $request){
        $Campaign = Campaign::findOrFail($id);

        $input =Arr::only($request->all(),['image']);
        $rules = [
            'image'=>'required|array|min:1',
            'image.*'=>'required|image'
        ];
        $input['campaign_id']=$id;
        $validator = Validator::make($input,$rules);
        if($validator->fails()){
           
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }
        foreach($request->file('image') as $image){
            $input['image']=upload($image,'campaign_banners/');
             
            Gallery::create($input);
        }
        
            flash()->ok("Gallery updated successfully !");
    
        
        return redirect()->back();
    }
    
    public function galleryDestroy($id){
        if(Gallery::findOrFail($id)->delete())
             return api()->success(['message'=>"Action completed successfully !"]);

        return api()->error();
        
    }
}

resources/views/campaigns/actions.blade.php
<div class='btn-group btn-group-sm'>
  <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('states.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  <a onclick="trashUtil(this)" trash-url="{{ route('states.destroy', $id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
    <i class="fa fa-trash"></i>
  </a>
</div>

resources/views/campaigns/create.blade.php
@extends('layouts.default')
@section('title','Add Campaign')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Add Campaign</h6> <a href="{{route('campaigns.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to NGOS</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('campaigns.store')}}" enctype="multipart/form-data">
                @include('campaigns.fields')
                <div class="row">
                  <div class="col-md-12 form-group">
                    <button type="submit" class="btn btn-info float-right">Create</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/campaigns/edit.blade.php
@extends('layouts.default')
@section('title','Edit Ngo')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Edit Ngo</h6> <a href="{{route('ngos.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to NGOs</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
            <form method="post" action="{{route('ngos.update',$Data->id)}}" enctype="multipart/form-data">
              @method('PUT')  
              @include('ngos.fields')
                <div class="col-md-12 form-group">
                  <button type="submit" class="btn btn-success float-right">Update</button>
                </div>
            </form>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

@endpush

resources/views/campaigns/fields.blade.php
<div class="row">
    {!! csrf_field() !!}
  
    <div class="col-md-6  col-sm-6 form-group">
        <label>Campaign Name</label>
        <input type="text" name="name"  class="form-control" value="{{old('name',$Data->name??'')}}" />
        <p class="error">
            {{$errors->first('name')}}
        </p>
    </div>
    

    <div class="col-md-6 col-sm-6  form-group">
        <label>Thumbnail</label>
        <input type="file" name="thumbnail" class="form-control" />
        <p class="error">
            {{$errors->first('thumbnail')}}
        </p>
    </div>
    

   

    <div class="col-md-4 col-sm-4 form-group">
        <label>Campaign Type</label>
        <select  class="form-control "   name="campaign_type_id">
            <option value="">Select</option>
            @foreach($types as $type)
            <option {{old('campaign_type_id',$Data->campaign_type_id??null)==$type->id?'selected':''}} value="{{$type->id}}">{{$type->name}}</option>
            @endforeach
        </select>
        <p class="error">
            {{$errors->first('campaign_type_id')}}
        </p>
    </div>

    <div class="col-md-8 col-sm-8 form-group">
        <label>Non Profit Organization</label>
        <select  class="form-control "   name="ngo_id">
            <option value="">Select</option>

            @foreach($ngos as $type)
            <option {{old('ngo_id',$Data->ngo_id??null)==$type->id?'selected':''}} value="{{$type->id}}">{{$type->name}}</option>
            @endforeach
        </select>
        <p class="error">
            {{$errors->first('ngo_id')}}
        </p>
    </div>
    

    <div class="col-md-4  col-sm-4 form-group">
        <label>No. of Meals</label>
        <input type="number" min="1" name="no_of_meals"  class="form-control" value="{{old('no_of_meals',$Data->no_of_meals??'')}}" />
        <p class="error">
            {{$errors->first('no_of_meals')}}
        </p>
    </div>

    <div class="col-md-4  col-sm-4 form-group">
        <label>Cost Per Meal</label>
        <input type="text"  name="cost_per_meal"  class="form-control" value="{{old('cost_per_meal',$Data->cost_per_meal??'')}}" />
        <p class="error">
            {{$errors->first('cost_per_meal')}}
        </p>
    </div>

    <div class="col-md-4  col-sm-4 form-group">
        <label>End Date</label>
        <input type="text"  name="end_date" autocomplete="off"  class="form-control _datepicker" value="{{old('end_date',$Data->end_date??'')}}" />
        <p class="error">
            {{$errors->first('end_date')}}
        </p>
    </div>

    <div class="col-md-12 col-sm-12 form-group">
        <label for="">Description</label>
        <textarea name="description" id="" class="form-control" >{{old('description',$Data->description??null)}}</textarea>
        <p class="error">
            {{$errors->first('description')}}
        </p>
    </div>

    

    
</div>

@push('scripts')
<script>
    const READY = ()=>{
        $('._datepicker').datepicker({
		language: 'en',
		dateFormat:"yyyy-mm-dd",
        minDate:new Date()
	});
    }
</script>
@endpush

resources/views/campaigns/gallery.blade.php
@extends('layouts.default')
@section('title','Gallery')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">{{$Campaign->name}}</h6> <a href="{{route('campaigns.index')}}" class="btn btn-default float-right"><i class="fa fa-arrow-left"></i>&nbsp;Back to Campaigns</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-header bg-success text-white text-center">
            Add Image to Gallery
        </div>
        <div class="card-body">
            <form action="" enctype="multipart/form-data" method="POST">
                <div class="row">
                    {!! csrf_field() !!}
                    <div class="col-md-4 col-sm-4 form-group">
                        <label for="">Image</label>
                        <input  type="file" multiple="multiple" name="image[]" class="form-control">
                        <p class="error">
                            {{$errors->first('image')}}
                        </p>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary rounded float-right">
                            Add Image
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>  
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
           <table class="table table-bordered table-striped">
               <thead>
                   <tr>
                       <th>#</th>
                       <th>Image</th>
                       <th>Actions</th>
                   </tr>
               </thead>
               <tbody>
                   @foreach($images as $i=>$image)
                    <tr>
                        <td>{{$i+1}}</td>
                        <td>
                           <img src="{{$image->image}}" style="max-height: 100px;" class="img img-responsive rounded" alt="">
                        </td>
                        <td>
                            <a onclick="trashUtil(this)" trash-url="{{ route('campaigns.gallery.destroy', $image->id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
                                <i class="fa fa-trash"></i>
                              </a>
                        </td>
                    </tr>
                   @endforeach
               </tbody>
           </table>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

<script>
   
</script>
@endpush

resources/views/campaigns/index.blade.php
@extends('layouts.default')
@section('title','Campaigns')
@section('header')
<div class="container-fluid">
  <div class="header-body">
    <div class="row align-items-center py-4">
      <div class="col-lg-12 col-12">
      <h6 class="h2 text-white d-inline-block mb-0">Campaigns</h6> <a href="{{route('campaigns.create')}}" class="btn btn-default float-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create Campaign</a>
      </div>
    </div>
    <!-- Card stats -->
    
  </div>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-xl-12">
    <div class="card">
        <div class="card-body table-responsive">
          <table class="table table-bordered table-striped d_table">
            <thead>
              <tr>
                <th>#</th>
                <th>Campaign</th>
                <th>Thumbnail</th>
                <th>Gallery</th>
                <th>Updated At</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              @foreach($data as $d)
                <tr>
                  <td>
                    {{$d->id}}
                  </td>
                  <td>
                    {{$d->name}}
                  </td>
                  <td>
                      <img src="{{$d->thumbnail}}" style="max-height:10vh;" class="rounded" alt="">
                      
                      
                  </td>
                  <td>
                    <a href="{{route('campaigns.gallery',$d->id)}}" class="btn btn-info btn-sm rounded">Gallery</a>
                  </td>
                  <td>
                    {!! getDateColumn($d) !!}
                  </td>
                  <td>
                    {{-- <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ route('ngos.edit', $d->id) }}" class='btn btn-link'>
                      <i class="fa fa-edit"></i>
                    </a>
                    <a onclick="trashUtil(this)" trash-url="{{ route('ngos.destroy', $d->id) }}" trash-item-to-remove="tr" data-toggle="tooltip" data-placement="bottom" title="Delete" href="javascript:void(0)" class='btn btn-link'>
                      <i class="fa fa-trash"></i>
                    </a> --}}
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
    </div>
  </div>
  
</div>
@endsection
@push('scripts')

<script>
   
</script>
@endpush